import { describe, it, expect } from 'vitest';
import {
  fetchJson,
  getNinjaExchangeOverview,
  getNinjaBuildIndex,
  getNinjaItemOverview,
  displayNinjaName,
  getPoe2dbPage,
  normalizeTrailingArabicToRoman,
  searchWiki,
  getWikiPage,
  decodeZoneCode,
  parseClientLog,
  decodePobCode,
  extractPobbinId,
  extractPoeNinjaId,
  fetchPobbinCode,
  fetchPoeNinjaCode,
  parseItemText,
  parsePobXml,
  comparePobBuilds,
  parsePoe2dbHtml,
  formatPoe2dbSections,
  searchPoe2scoutUniques,
  lookupUniquePriceFromScout,
  mapItemClassToScoutCategory,
  getPoe2scoutUniques,
} from './api.js';

describe('api.ts barrel re-exports', () => {
  it.each([
    { name: 'fetchJson', value: fetchJson },
    { name: 'getNinjaExchangeOverview', value: getNinjaExchangeOverview },
    { name: 'getNinjaBuildIndex', value: getNinjaBuildIndex },
    { name: 'getNinjaItemOverview', value: getNinjaItemOverview },
    { name: 'displayNinjaName', value: displayNinjaName },
    { name: 'getPoe2dbPage', value: getPoe2dbPage },
    { name: 'normalizeTrailingArabicToRoman', value: normalizeTrailingArabicToRoman },
    { name: 'searchWiki', value: searchWiki },
    { name: 'getWikiPage', value: getWikiPage },
    { name: 'decodeZoneCode', value: decodeZoneCode },
    { name: 'parseClientLog', value: parseClientLog },
    { name: 'decodePobCode', value: decodePobCode },
    { name: 'extractPobbinId', value: extractPobbinId },
    { name: 'extractPoeNinjaId', value: extractPoeNinjaId },
    { name: 'fetchPobbinCode', value: fetchPobbinCode },
    { name: 'fetchPoeNinjaCode', value: fetchPoeNinjaCode },
    { name: 'parseItemText', value: parseItemText },
    { name: 'parsePobXml', value: parsePobXml },
    { name: 'comparePobBuilds', value: comparePobBuilds },
    { name: 'parsePoe2dbHtml', value: parsePoe2dbHtml },
    { name: 'formatPoe2dbSections', value: formatPoe2dbSections },
    { name: 'searchPoe2scoutUniques', value: searchPoe2scoutUniques },
    { name: 'lookupUniquePriceFromScout', value: lookupUniquePriceFromScout },
    { name: 'mapItemClassToScoutCategory', value: mapItemClassToScoutCategory },
    { name: 'getPoe2scoutUniques', value: getPoe2scoutUniques },
  ])('re-exports $name as a function', ({ value }) => {
    expect(typeof value).toBe('function');
  });
});
