name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    concurrency:
      # Cancel any currently running job or workflow in the same concurrency group.
      # The group is a unique identifier for the workflow run.
      #
      # Explanation:
      # - github.workflow: The name of the workflow (e.g. Workflow 1).
      # - github.event.pull_request.number: The number of the pull request (when the trigger event is a PR).
      # - github.ref: The branch name (when the trigger is not a PR but a push).
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run prettier
        run: npm run format:check

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npm run typecheck

      - name: Audit packages
        run: npm audit --omit=dev --audit-level=high

      - name: Run unit tests
        run: npm run test:coverage

      - name: Upload code coverage
        if: ${{ !cancelled() && success() }}
        uses: codecov/codecov-action@v5
        with:
          directory: coverage
          report_type: coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && success() }}
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Success Reporting
        if: ${{ !cancelled() && success() }}
        run: |
          echo "CI succeeded. Recent commits:"
          git log -5 --oneline
